const ws=document.getElementById('workspace'), lanesEl=document.getElementById('lanes'), nodesEl=document.getElementById('nodes'), svg=document.getElementById('connections');
let state={lanes:[{id:'l1',name:'Solicitante',y:0,h:210},{id:'l2',name:'Área',y:210,h:210},{id:'l3',name:'Executor',y:420,h:260}],nodes:[],conns:[],zoom:1};
let selected=null, connectMode=false, firstConnect=null, drag=null;
const uid=()=>Math.random().toString(36).slice(2,9);
function init(){ws.dataset.title=document.getElementById('processTitle').value; if(!localStorage.flowprocessSeen){seed(); localStorage.flowprocessSeen='1'} render();}
function seed(){state.nodes=[
{id:uid(),type:'start',text:'Início',x:30,y:90},{id:uid(),type:'task',text:'Solicitar\nDemanda',x:130,y:55},{id:uid(),type:'task',text:'Triar / Receber\nDemanda',x:130,y:270},{id:uid(),type:'task',text:'Revisar\nsolicitação',x:315,y:55},{id:uid(),type:'decision',text:'Aprov?',x:330,y:285},{id:uid(),type:'task',text:'Desenvolver\na solicitação',x:310,y:500},{id:uid(),type:'task',text:'Revisar entrega',x:560,y:270},{id:uid(),type:'decision',text:'Revisar?',x:600,y:505},{id:uid(),type:'task',text:'Receber\ndemanda',x:840,y:55},{id:uid(),type:'decision',text:'Ajuste?',x:870,y:285},{id:uid(),type:'task',text:'Realizar ajustes',x:840,y:500},{id:uid(),type:'end',text:'Fim',x:1120,y:285}];
const n=state.nodes; state.conns=[[0,1],[1,2],[2,3],[3,4],[4,5],[5,7],[7,6],[6,9],[9,10],[10,9],[9,8],[8,11]].map(([a,b])=>({id:uid(),from:n[a].id,to:n[b].id}));}
function render(){lanesEl.innerHTML='';nodesEl.innerHTML=''; ws.style.transform=`scale(${state.zoom})`; document.getElementById('zoomText').textContent=Math.round(state.zoom*100)+'%'; svg.setAttribute('height',ws.scrollHeight); svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#111"/></marker></defs>';
state.lanes.forEach(l=>{let d=document.createElement('div');d.className='lane';d.style.top=l.y+'px';d.style.height=l.h+'px';d.innerHTML=`<div class="lane-label"><span class="lane-name" contenteditable>${l.name}</span></div>`;d.querySelector('.lane-name').oninput=e=>l.name=e.target.textContent;lanesEl.appendChild(d)});
state.conns.forEach(c=>drawConn(c)); state.nodes.forEach(n=>{let el=document.createElement('div');el.className='node '+n.type+(selected===n.id?' selected':'');el.style.left=n.x+'px';el.style.top=n.y+'px';el.dataset.id=n.id;el.innerHTML=`<span class="text">${n.text.replace(/\n/g,'<br>')}</span>`;el.onpointerdown=startDrag;el.ondblclick=editNode;el.onclick=nodeClick;nodesEl.appendChild(el)});}
function center(n){let w=n.type==='decision'?76:n.type==='start'||n.type==='end'?38:128,h=n.type==='decision'?76:n.type==='start'||n.type==='end'?38:76; return {x:n.x+w/2,y:n.y+h/2}}
function drawConn(c){let a=state.nodes.find(n=>n.id===c.from),b=state.nodes.find(n=>n.id===c.to); if(!a||!b)return; let p=center(a),q=center(b); let path=document.createElementNS('http://www.w3.org/2000/svg','path'); path.setAttribute('class','conn'); path.setAttribute('d',`M ${p.x} ${p.y} L ${q.x} ${q.y}`); svg.appendChild(path)}
function nodeClick(e){e.stopPropagation();let id=e.currentTarget.dataset.id; if(connectMode){ if(!firstConnect){firstConnect=id; selected=id}else if(firstConnect!==id){state.conns.push({id:uid(),from:firstConnect,to:id}); connectMode=false; firstConnect=null; selected=id} render(); return;} selected=id; render()}
function startDrag(e){if(connectMode)return; let id=e.currentTarget.dataset.id,n=state.nodes.find(x=>x.id===id); selected=id; drag={id,startX:e.clientX,startY:e.clientY,x:n.x,y:n.y}; e.currentTarget.setPointerCapture(e.pointerId)}
window.onpointermove=e=>{if(!drag)return; let n=state.nodes.find(x=>x.id===drag.id); n.x=Math.max(5,drag.x+(e.clientX-drag.startX)/state.zoom); n.y=Math.max(5,drag.y+(e.clientY-drag.startY)/state.zoom); render()}; window.onpointerup=()=>drag=null; ws.onclick=()=>{selected=null;render()};
function editNode(e){e.stopPropagation(); let id=e.currentTarget.dataset.id,n=state.nodes.find(x=>x.id===id); let val=prompt('Texto do bloco:',n.text.replace(/\n/g,' ')); if(val!==null){n.text=val; render()}}
document.querySelectorAll('.palette button').forEach(b=>b.onclick=()=>{state.nodes.push({id:uid(),type:b.dataset.type,text:b.textContent.replace(/[●▣◇▤]/g,'').trim(),x:180,y:90});render()});
document.getElementById('addLaneBtn').onclick=()=>{let last=state.lanes[state.lanes.length-1];state.lanes.push({id:uid(),name:'Nova área',y:last.y+last.h,h:210});ws.style.minHeight=(last.y+last.h+230)+'px';render()};
document.getElementById('connectBtn').onclick=()=>{connectMode=true;firstConnect=null;alert('Selecione o primeiro bloco e depois o segundo para criar a seta.')};
document.getElementById('duplicateBtn').onclick=()=>{let n=state.nodes.find(x=>x.id===selected); if(n){state.nodes.push({...n,id:uid(),x:n.x+30,y:n.y+30});render()}};
document.getElementById('deleteBtn').onclick=()=>{if(!selected)return; state.nodes=state.nodes.filter(n=>n.id!==selected); state.conns=state.conns.filter(c=>c.from!==selected&&c.to!==selected); selected=null;render()};
document.getElementById('clearBtn').onclick=()=>{if(confirm('Limpar o processo atual?')){state.nodes=[];state.conns=[];render()}};
document.getElementById('saveBtn').onclick=()=>{localStorage.flowprocess=JSON.stringify(state);alert('Salvo neste navegador.')};
document.getElementById('loadBtn').onclick=()=>{let s=localStorage.flowprocess;if(s){state=JSON.parse(s);render()}else alert('Nenhum projeto salvo.')};
document.getElementById('zoomIn').onclick=()=>{state.zoom=Math.min(1.5,state.zoom+.1);render()};document.getElementById('zoomOut').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.1);render()};
document.getElementById('processTitle').oninput=e=>ws.dataset.title=e.target.value;
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
async function capture(){let old=state.zoom;state.zoom=1;render();await new Promise(r=>setTimeout(r,100));let canvas=await html2canvas(ws,{backgroundColor:'#ffffff',scale:2});state.zoom=old;render();return canvas}
document.getElementById('exportPngBtn').onclick=async()=>{let c=await capture();let a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='processo-flowprocess.png';a.click()};
document.getElementById('exportPdfBtn').onclick=async()=>{let c=await capture();let img=c.toDataURL('image/png');let {jsPDF}=window.jspdf;let pdf=new jsPDF('l','mm','a4');let w=297,h=c.height*297/c.width;pdf.addImage(img,'PNG',0,0,w,Math.min(h,210));pdf.save('processo-flowprocess.pdf')};
init();
