const canvas=document.getElementById('canvas'), lanesEl=document.getElementById('lanes'), svg=document.getElementById('lines');
let lanes=['Solicitante','Área de Compras','Financeiro','Fornecedor'];
let nodes=[], conns=[], selected=null, selectedType=null, mode='select', connectFrom=null, zoom=1, id=1;
const defaults={start:['Início',90,50],task:['Nova tarefa',170,36],decision:['Aprovado?',350,34],end:['Fim',1180,55],note:['Anotação',250,36]};
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function render(){lanesEl.innerHTML='';lanes.forEach((name,i)=>{const l=document.createElement('div');l.className='lane';l.style.height='190px';const title=document.createElement('div');title.className='lane-title';title.textContent=name;title.ondblclick=()=>{const n=prompt('Nome da raia:',name);if(n){lanes[i]=n;render();}};l.appendChild(title);lanesEl.appendChild(l)});nodes.forEach(drawNode);drawLines();updateCount()}
function drawNode(n){const el=document.createElement('div');el.className='node '+n.type+(selected===n.id&&selectedType==='node'?' selected':'');el.style.left=n.x+'px';el.style.top=n.y+'px';el.dataset.id=n.id;el.innerHTML='<span class="text">'+n.text+'</span>';el.onmousedown=startDrag;el.onclick=e=>{e.stopPropagation(); if(mode==='connect') connect(n.id); else select('node',n.id)};el.ondblclick=e=>{e.stopPropagation(); const txt=prompt('Editar texto:',n.text); if(txt!==null){n.text=txt;render();}};lanesEl.appendChild(el)}
function center(n){const w=n.type==='task'?110:n.type==='decision'?76:n.type==='note'?150:54; const h=n.type==='task'?70:n.type==='decision'?76:n.type==='note'?95:54; return {x:n.x+w/2,y:n.y+h/2}}
function drawLines(){svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#111827"/></marker></defs>';conns.forEach(c=>{let a=nodes.find(n=>n.id===c.from),b=nodes.find(n=>n.id===c.to); if(!a||!b)return;let p=center(a),q=center(b);const line=document.createElementNS('http://www.w3.org/2000/svg','path');line.setAttribute('d',`M ${p.x} ${p.y} L ${q.x} ${q.y}`);line.setAttribute('stroke',c.id===selected&&selectedType==='conn'?'#1e74d6':'#111827');line.setAttribute('stroke-width',c.id===selected&&selectedType==='conn'?4:2);line.setAttribute('fill','none');line.setAttribute('marker-end','url(#arrow)');line.classList.add('connector');line.style.pointerEvents='stroke';line.onclick=e=>{e.stopPropagation();select('conn',c.id)};svg.appendChild(line)})}
function addNode(type){let d=defaults[type], laneTop=Math.min(570,20+nodes.length%4*190);nodes.push({id:'n'+id++,type,text:d[0],x:d[1]+nodes.length*22,y:laneTop+d[2]});render();toast('Elemento adicionado')}
function addLane(){lanes.push('Nova Raia');render();toast('Raia adicionada')}
function select(t,i){selectedType=t;selected=i;render()}
function connect(nid){if(!connectFrom){connectFrom=nid;select('node',nid);toast('Escolha o destino da seta')}else if(connectFrom!==nid){conns.push({id:'c'+id++,from:connectFrom,to:nid});connectFrom=null;render();toast('Conexão criada')}}
function startDrag(e){if(mode==='connect')return;e.preventDefault();const nid=this.dataset.id,n=nodes.find(x=>x.id===nid);select('node',nid);let sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;function move(ev){n.x=ox+(ev.clientX-sx)/zoom;n.y=oy+(ev.clientY-sy)/zoom;n.x=Math.max(62,n.x);n.y=Math.max(8,n.y);render()}function up(){document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up)}document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
function del(){if(selectedType==='node'){nodes=nodes.filter(n=>n.id!==selected);conns=conns.filter(c=>c.from!==selected&&c.to!==selected)} if(selectedType==='conn')conns=conns.filter(c=>c.id!==selected);selected=null;selectedType=null;render();}
function updateCount(){document.getElementById('countEls').textContent='Elementos: '+nodes.length;document.getElementById('countConns').textContent='Conexões: '+conns.length;document.getElementById('zoomLabel').textContent=Math.round(zoom*100)+'%';document.getElementById('statusZoom').textContent=Math.round(zoom*100)+'%'}
function save(){localStorage.setItem('flowprocess-pro',JSON.stringify({title:processTitle.value,lanes,nodes,conns,id}));toast('Salvo no navegador')}
function load(){const s=localStorage.getItem('flowprocess-pro');if(!s)return toast('Nada salvo');const d=JSON.parse(s);processTitle.value=d.title||'';lanes=d.lanes||lanes;nodes=d.nodes||[];conns=d.conns||[];id=d.id||1;render();toast('Carregado')}
async function exportPNG(){select(null,null);await html2canvas(canvas,{backgroundColor:'#fff',scale:2}).then(c=>{const a=document.createElement('a');a.href=c.toDataURL();a.download='processo.png';a.click()})}
async function exportPDF(){select(null,null);const c=await html2canvas(canvas,{backgroundColor:'#fff',scale:2});const img=c.toDataURL('image/png');const {jsPDF}=window.jspdf;const pdf=new jsPDF('l','mm','a4');const w=297,h=c.height*297/c.width;pdf.addImage(img,'PNG',0,0,w,Math.min(210,h));pdf.save('processo.pdf')}
function seed(){nodes=[{id:'n1',type:'start',text:'Início',x:92,y:50},{id:'n2',type:'task',text:'Solicitar\ncompra',x:170,y:40},{id:'n3',type:'task',text:'Enviar\nsolicitação',x:350,y:40},{id:'n4',type:'task',text:'Analisar\nsolicitação',x:330,y:235},{id:'n5',type:'decision',text:'Aprovado?',x:520,y:230},{id:'n6',type:'task',text:'Enviar para\naprovação',x:660,y:235},{id:'n7',type:'task',text:'Aprovar\norçamento',x:690,y:425},{id:'n8',type:'decision',text:'Aprovado?',x:850,y:420},{id:'n9',type:'task',text:'Emitir ordem\nde compra',x:1040,y:435},{id:'n10',type:'task',text:'Receber ordem\nde compra',x:820,y:625},{id:'n11',type:'task',text:'Confirmar\nrecebimento',x:1040,y:625},{id:'n12',type:'end',text:'Fim',x:1250,y:640},{id:'n13',type:'note',text:'Anotação\n\nProcesso padrão para solicitação de compras.',x:250,y:610}];conns=[{id:'c1',from:'n1',to:'n2'},{id:'c2',from:'n2',to:'n3'},{id:'c3',from:'n3',to:'n4'},{id:'c4',from:'n4',to:'n5'},{id:'c5',from:'n5',to:'n6'},{id:'c6',from:'n6',to:'n7'},{id:'c7',from:'n7',to:'n8'},{id:'c8',from:'n8',to:'n9'},{id:'c9',from:'n9',to:'n10'},{id:'c10',from:'n10',to:'n11'},{id:'c11',from:'n11',to:'n12'}];id=30;render()}
document.querySelectorAll('.add').forEach(b=>b.onclick=()=>addNode(b.dataset.type));addLaneBtn.onclick=addLane;deleteBtn.onclick=del;saveBtn.onclick=save;loadBtn.onclick=load;pngBtn.onclick=exportPNG;pdfBtn.onclick=exportPDF;clearBtn.onclick=()=>{if(confirm('Limpar tudo?')){nodes=[];conns=[];render()}};connectBtn.onclick=()=>{mode=mode==='connect'?'select':'connect';connectBtn.classList.toggle('on',mode==='connect');connectFrom=null};selectBtn.onclick=()=>{mode='select';connectBtn.classList.remove('on')};canvas.onclick=()=>{selected=null;selectedType=null;render()};document.onkeydown=e=>{if(e.key==='Delete')del()};zoomIn.onclick=()=>{zoom=Math.min(1.6,zoom+.1);canvas.style.transform=`scale(${zoom})`;updateCount()};zoomOut.onclick=()=>{zoom=Math.max(.5,zoom-.1);canvas.style.transform=`scale(${zoom})`;updateCount()};
seed();
